config/routes.rb
Album::Application.routes.draw do

  
get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "users#new", :as => "sign_up"

root :to =>'users#index'
resources :users

  resources :albumms

  resources :sessions

end

app/models/albumm.rb
class Albumm < ActiveRecord::Base
  attr_accessible :description, :name,:user_id,:image
  belongs_to :user
   mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :password, :password_confirmation
  has_many :albumms

  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :name
  validates_uniqueness_of :name
  
  def self.authenticate(name, password)
    user = find_by_name(name)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/albumms_controller.rb
class AlbummsController < ApplicationController
  # GET /albumms
  # GET /albumms.json
  before_filter :require_user,:except=>[:new,:create]
  def index
    @albumms = Albumm.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @albumms }
    end
  end

  # GET /albumms/1
  # GET /albumms/1.json
  def show
    @albumm = Albumm.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @albumm }
    end
  end

  # GET /albumms/new
  # GET /albumms/new.json
  def new
    @albumm = Albumm.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @albumm }
    end
  end

  # GET /albumms/1/edit
  def edit
    @albumm = Albumm.find(params[:id])
  end

  # POST /albumms
  # POST /albumms.json
  def create
    @albumm = Albumm.new(params[:albumm])

    respond_to do |format|
      if @albumm.save
        format.html { redirect_to @albumm, notice: 'Albumm was successfully created.' }
        format.json { render json: @albumm, status: :created, location: @albumm }
      else
        format.html { render action: "new" }
        format.json { render json: @albumm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /albumms/1
  # PUT /albumms/1.json
  def update
    @albumm = Albumm.find(params[:id])

    respond_to do |format|
      if @albumm.update_attributes(params[:albumm])
        format.html { redirect_to @albumm, notice: 'Albumm was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @albumm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albumms/1
  # DELETE /albumms/1.json
  def destroy
    @albumm = Albumm.find(params[:id])
    @albumm.destroy

    respond_to do |format|
      format.html { redirect_to albumms_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :current_user

private

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end

def require_user
		if current_user.blank? 	 	
			redirect_to root_url,:notice=>"You must login to access this page"
		end		
	end  
	end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	 before_filter :require_user,:except=>[:new,:create]
  def new
  end
  def create
  user = User.authenticate(params[:name], params[:password])
  if user
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Logged in!"
  else
    flash.now.alert = "Invalid name or password"
    render "new"
  end
end

def destroy
  session[:user_id] = nil
  redirect_to root_url, :notice => "Logged out!"
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
   #before_filter :require_user,:except=>[:new,:create]
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  
  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
  end
end
=begin
  
rescue Exception => e
  
end
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

=end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/albumms_helper.rb
module AlbummsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albumms/_form.html.erb
<%= form_for(@albumm) do |f| %>
  <% if @albumm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@albumm.errors.count, "error") %> prohibited this albumm from being saved:</h2>

      <ul>
      <% @albumm.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :image%><br />
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/albumms/edit.html.erb
<h1>Editing albumm</h1>

<%= render 'form' %>

<%= link_to 'Show', @albumm %> |
<%= link_to 'Back', albumms_path %>

app/views/albumms/index.html.erb
<h1>Listing albumms</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @albumms.each do |albumm| %>
  <tr>
    <td><%= albumm.name %></td>
    <td><%= albumm.description %></td>
    <td><%= link_to 'Show', albumm %></td>
    <td><%= link_to 'Edit', edit_albumm_path(albumm) %></td>
    <td><%= link_to 'Destroy', albumm, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Albumm', new_albumm_path %>

app/views/albumms/new.html.erb
<h1>New albumm</h1>

<%= render 'form' %>

<%= link_to 'Back', albumms_path %>

app/views/albumms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @albumm.name %>
</p>

<p>
  <b>Description:</b>
  <%= @albumm.description %>
</p>


<%= link_to 'Edit', edit_albumm_path(@albumm) %> |
<%= link_to 'Back', albumms_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Album</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="user_nav">
  <% if current_user %>
    Logged in as <%= current_user.name %>.
    <%= link_to "Log out", log_out_path %>
  <% else %>
    <%= link_to "Sign up", sign_up_path %> or
    <%= link_to "log in", log_in_path %>
  <% end %>
</div>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>


<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.text_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>
<p id="notice"><%= notice %></p>
<table>
  <tr>
    <th>Name</th>
    <th>Password </th>
    <th>Password Confirmation</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.password %></td>
    <td><%= user.password_confirmation%></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Password hash:</b>
  <%= @user.password %>
</p>

<p>
  <b>Password salt:</b>
  <%= @user.password_confirmation %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>